### ISSUE TITLE
Can AnomalyDetection detect Linear growth?

### ISSUE THREAD

**Issue by Chernfalin** [twitter/AnomalyDetection#109]
I saw a contradiction describe here:
https://anomaly.io/anomaly-detection-twitter-r/
###
What anomalies can be detected?:
[Anomaly not detected] Linear growth
###

**Comment by rafaelschlatter** [comment]
> I saw a contradiction describe here:
> https://anomaly.io/anomaly-detection-twitter-r/

Contradictory to what? I didn't study the code in detail, but it looks like they are decomposing the time series into seasonal, trend and residual component. The anomaly detection algorithm is then applied on the residual component. A linear growth is most likely captured in the trend, and hence will not be flagged as an anomaly.
