### ISSUE TITLE
detect_anoms erroneously reports at least one anomaly, regardless of data

### ISSUE THREAD

**Issue by andrewclegg** [twitter/AnomalyDetection#24]
I think I've found a bug in `detect_anoms`.

Before the main loop, [`num_anoms` is initialized to 0](https://github.com/twitter/AnomalyDetection/blob/master/R/detect_anoms.R#L65).

At the end of each iteration, [you update `num_anoms` if R is greater than lambda](https://github.com/twitter/AnomalyDetection/blob/master/R/detect_anoms.R#L101).

Then after the loop, [you return `R_idx[1L:num_anoms]`](https://github.com/twitter/AnomalyDetection/blob/master/R/detect_anoms.R#L105).

So if no elements made R exceed lambda, the return value works out to `R_idx[1L:0L]`. But this range subscript gives you the first element, not an empty vector:

```
> foo = c(4,5,6,7)
> foo[1:0]
[1] 4
>
```

So won't it always report the most extreme value as an outlier, no matter what data you give it? (Of course the user won't see this if they've set a threshold in `AnomalyDetection`, but they might not do that...)

**Comment by jhochenbaum** [comment]
Sounds like a bug to me! Owen and I are looking into this tonight and we'll issue a patch, thanks again and nice detective work.

**Comment by owenvallis** [comment]
Hi Andrew,

Thanks for the heads up. We now set R_idx to NULL if there are 0 anoms detected.

**Comment by andrewclegg** [comment]
Thanks for the quick response!

**Comment by jhochenbaum** [comment]
Cheers!
