### ISSUE TITLE
License for AnomalyDetection

### ISSUE THREAD

**Issue by ercmilla** [twitter/AnomalyDetection#33]
Is there any chance of this going under another open source license, say MIT?

**Comment by caniszczyk** [comment]
It would be hard for us to move to something other than the GPL based on our GPL-based dependencies (e.g., https://github.com/hadley/lubridate/blob/master/DESCRIPTION)

If you're running code on the server side (not distributing it... it shouldn't matter).

Also, the R community tends to favor the GPL in many instances.
