### ISSUE TITLE
csv import

### ISSUE THREAD

**Issue by Pascougnou** [twitter/AnomalyDetection#41]
Hello

I might be asking a dumb question but I tried to use my brain and it failed ;-)
When trying to use the library I import data from a .csv (`data_raw <- read.csv(file = file_name, header = FALSE, sep = ","` ). 
I get a table with two raws, one containing a timestamp and the second a value.

My problem is whenerver I try `res = AnomalyDetectionTs(data_raw, max_anoms=0.02, direction='both', plot=TRUE` 
or `res = AnomalyDetectionVer(data_raw[1], max_anoms=0.02, direction='both', plot=TRUE` 
I get `Error in Summary.factor(1:339, na.rm = FALSE) : ‘max’ not meaningful for factors`

Any help is welcomed. 
Thanks. 

EDIT: an extract of my .csv
`"2013-12-17","0.480000"
"2013-12-18","18.432416"
"2013-12-19","30.263850"
"2013-12-20","6.247121"
"2013-12-21","127.504873"
"2013-12-22","7.163464"
"2013-12-23","8.275153"
"2013-12-24","104.615116"
"2013-12-25","0.003541"
"2013-12-26","19.591689"
"2013-12-27","20.010327"
"2013-12-28","33.474902"
"2013-12-29","59.807252"
"2013-12-30","9.476524"
"2013-12-31","114.014947"
"2014-01-01","1.009808"
`

**Comment by LJTURNER** [comment]
Hi @Pascougnou - I realise this thread was initiated some time ago now, however I am finding that I come across the same error when trying to run the anomaly detection on data I have imported from a tab delimited text file.

I also have a table consisting of a timestamp and the value I want to test.

Did you encounter a solution to this? I'd appreciate any help, as I am a relatively inexperienced R user.

Many Thanks!

**Comment by LJTURNER** [comment]
An update for those viewing this post - my mistake was to bring in stringsAsFactors=TRUE, changing this to FALSE resolves the issue.

UK <- read.csv("C:/Temp/UK.txt", stringsAsFactors=FALSE)

**Comment by Pascougnou** [comment]
Hi @LJTURNER some time ago indeed ;-) 

I was looking through my files but you were quicker. 
Thanks.
