### ISSUE TITLE
Error while running from Rscript

### ISSUE THREAD

**Issue by prathik** [twitter/AnomalyDetection#64]
AnomalyDetectionTs works file on the R gui however if I run it as a script I am getting the following error

Error in initFields(scales = scales) :
  could not find function "initRefFields"
Calls: AnomalyDetectionTs ... initialize -> initialize -> <Anonymous> -> initFields
Execution halted

The same thing in the script worked fine in the GUI.

**Comment by joaoborges** [comment]
Hi, 

I had a similar issue with Rscript, but with another output error ( #76 ).

To fix it, I just included `library(methods)`.

Maybe this could be your case too.
