### ISSUE TITLE
Error when granularity is daily and only_last is null

### ISSUE THREAD

**Issue by adamatw** [twitter/AnomalyDetection#8]
There's seems to be a bug for data with daily granularity. If gran == day, AnomalyDetectionTs does a check:

if(only_last == 'hr')

However, only_last can also be null. If it is, this check generates an error which keeps AnomalyDetectionTs from finishing:

Error in if (only_last == "hr") { : argument is of length zero

I submitted a pull request which fixes the problem by checking only_last for null first.

Also, thanks for a super package.

**Comment by jhochenbaum** [comment]
Thanks!

**Comment by jhochenbaum** [comment]
@owenvallis checked in a similar patch just now - thanks again for the initial patch and pointing this out @adamatw

**Comment by adamatw** [comment]
Looks good to me -- thanks!
